# Generated by Django 5.0.1 on 2024-02-27 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminumEtch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('alum_etch_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('alum_etch_time', models.CharField(blank=True, max_length=400, null=True)),
                ('stir_rpm', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_alum_etch_depth', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_photoresist_peeling', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_aluminum_peeling', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AluminumEvaporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('aluminum_evaporation_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('aluminum_evaporation_time', models.CharField(blank=True, max_length=400, null=True)),
                ('pressure_before_start_seq', models.CharField(blank=True, max_length=400, null=True)),
                ('pressure_before_evaporation', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_layer_thickness', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_layer_thick_qcm', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_deposition_rate', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChipList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('cleaning_step', models.CharField(blank=True, max_length=400, null=True)),
                ('days_p504_at_room_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('prebake_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('prebake_time', models.CharField(blank=True, max_length=400, null=True)),
                ('amount_drops', models.CharField(blank=True, max_length=400, null=True)),
                ('spin_rpm', models.CharField(blank=True, max_length=400, null=True)),
                ('spin_time', models.CharField(blank=True, max_length=400, null=True)),
                ('bake_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('bake_time', models.CharField(blank=True, max_length=400, null=True)),
                ('humidity', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_layer_thickness', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_cracking', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_particles', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OxideEtch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('max_temp_glass_reached', models.CharField(blank=True, max_length=400, null=True)),
                ('oxide_etch_time', models.CharField(blank=True, max_length=400, null=True)),
                ('oxide_etch_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_oxide_etch_depth', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patterning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('underlying_material', models.CharField(blank=True, max_length=400, null=True)),
                ('hdms_prebake_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('hdms_prebake_time', models.CharField(blank=True, max_length=400, null=True)),
                ('hdms_spin_rpm', models.CharField(blank=True, max_length=400, null=True)),
                ('hdms_spin_time', models.CharField(blank=True, max_length=400, null=True)),
                ('hdms_bake_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('hdms_bake_time', models.CharField(blank=True, max_length=400, null=True)),
                ('photoresist_spin_rpm', models.CharField(blank=True, max_length=400, null=True)),
                ('photoresist_spin_time', models.CharField(blank=True, max_length=400, null=True)),
                ('photoresist_bake_temp', models.CharField(blank=True, max_length=400, null=True)),
                ('photoresist_bake_time', models.CharField(blank=True, max_length=400, null=True)),
                ('exposure_pattern', models.CharField(blank=True, max_length=400, null=True)),
                ('exposure_time', models.CharField(blank=True, max_length=400, null=True)),
                ('develop_time', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_pattern_quality', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_leftover_photoresist', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_missing_photoresist', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_contaminants', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlasmaClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('o2_flow', models.CharField(blank=True, max_length=400, null=True)),
                ('rf_power', models.CharField(blank=True, max_length=400, null=True)),
                ('clean_time', models.CharField(blank=True, max_length=400, null=True)),
                ('metric_contaminants', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlasmaEtch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_number', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('o2_flow', models.CharField(blank=True, max_length=400, null=True)),
                ('sf6_flow', models.CharField(blank=True, max_length=400, null=True)),
                ('rf_power', models.CharField(blank=True, max_length=400, null=True)),
                ('etch_time', models.CharField(blank=True, max_length=400, null=True)),
                ('etch_depth', models.CharField(blank=True, max_length=400, null=True)),
                ('metrology_link', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('chip_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
