# Generated by Django 5.0.1 on 2024-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiplist',
            name='content_type',
            field=models.CharField(default='image/png', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chiplist',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
